# Generated by Django 4.0.3 on 2022-04-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Concelear', 'Concelear'), ('Blush', 'Blush'), ('Eyeshadow', 'Eyeshadow'), ('Eyeliner', 'Eyeliner'), ('Lipstick', 'Lipstick'), ('Lipgloss', 'Lipgloss'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
