# Generated by Django 4.0.3 on 2022-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Concealer', 'Concealer'), ('Blush', 'Blush'), ('Eyeshadow', 'Eyeshadow'), ('Eyeliner', 'Eyeliner'), ('Lipstick', 'Lipstick'), ('Lipgloss', 'Lipgloss'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
