# Generated by Django 4.0.3 on 2022-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_photo_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
